/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 04-Dec-2016 6:51:02 PM 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Views */

DROP VIEW IF EXISTS `gn_payment_history_view` CASCADE
;

/* Drop Tables */

DROP TABLE IF EXISTS `gn_address_type` CASCADE
;

DROP TABLE IF EXISTS `gn_assn_bill_schedule` CASCADE
;

DROP TABLE IF EXISTS `gn_assn_billing_settings` CASCADE
;

DROP TABLE IF EXISTS `gn_assn_discount_rule` CASCADE
;

DROP TABLE IF EXISTS `gn_association` CASCADE
;

DROP TABLE IF EXISTS `gn_association_customer` CASCADE
;

DROP TABLE IF EXISTS `gn_association_facility` CASCADE
;

DROP TABLE IF EXISTS `gn_association_log` CASCADE
;

DROP TABLE IF EXISTS `gn_association_login_type` CASCADE
;

DROP TABLE IF EXISTS `gn_association_migration` CASCADE
;

DROP TABLE IF EXISTS `gn_association_settings` CASCADE
;

DROP TABLE IF EXISTS `gn_association_zip_code` CASCADE
;

DROP TABLE IF EXISTS `gn_bill_adjustment_type` CASCADE
;

DROP TABLE IF EXISTS `gn_bill_status` CASCADE
;

DROP TABLE IF EXISTS `gn_calendar_year_type` CASCADE
;

DROP TABLE IF EXISTS `gn_club_bill` CASCADE
;

DROP TABLE IF EXISTS `gn_club_bill_adjustment` CASCADE
;

DROP TABLE IF EXISTS `gn_club_contact_type` CASCADE
;

DROP TABLE IF EXISTS `gn_club_customer_field` CASCADE
;

DROP TABLE IF EXISTS `gn_club_field` CASCADE
;

DROP TABLE IF EXISTS `gn_club_payment` CASCADE
;

DROP TABLE IF EXISTS `gn_club_payment_check` CASCADE
;

DROP TABLE IF EXISTS `gn_club_payment_detail` CASCADE
;

DROP TABLE IF EXISTS `gn_club_service` CASCADE
;

DROP TABLE IF EXISTS `gn_club_service_contact` CASCADE
;

DROP TABLE IF EXISTS `gn_club_service_customer` CASCADE
;

DROP TABLE IF EXISTS `gn_club_service_settings` CASCADE
;

DROP TABLE IF EXISTS `gn_contact_type` CASCADE
;

DROP TABLE IF EXISTS `gn_course` CASCADE
;

DROP TABLE IF EXISTS `gn_course_customer_link` CASCADE
;

DROP TABLE IF EXISTS `gn_course_hole` CASCADE
;

DROP TABLE IF EXISTS `gn_course_link_type` CASCADE
;

DROP TABLE IF EXISTS `gn_course_score` CASCADE
;

DROP TABLE IF EXISTS `gn_course_tee` CASCADE
;

DROP TABLE IF EXISTS `gn_customer` CASCADE
;

DROP TABLE IF EXISTS `gn_customer_address` CASCADE
;

DROP TABLE IF EXISTS `gn_customer_contact` CASCADE
;

DROP TABLE IF EXISTS `gn_customer_golf_clubs` CASCADE
;

DROP TABLE IF EXISTS `gn_customer_lead_status` CASCADE
;

DROP TABLE IF EXISTS `gn_customer_link` CASCADE
;

DROP TABLE IF EXISTS `gn_customer_link_type` CASCADE
;

DROP TABLE IF EXISTS `gn_customer_pay_method` CASCADE
;

DROP TABLE IF EXISTS `gn_customer_role` CASCADE
;

DROP TABLE IF EXISTS `gn_email_template` CASCADE
;

DROP TABLE IF EXISTS `gn_facility` CASCADE
;

DROP TABLE IF EXISTS `gn_facility_type` CASCADE
;

DROP TABLE IF EXISTS `gn_fee_level` CASCADE
;

DROP TABLE IF EXISTS `gn_fee_type` CASCADE
;

DROP TABLE IF EXISTS `gn_gender_type` CASCADE
;

DROP TABLE IF EXISTS `gn_golf_club_type` CASCADE
;

DROP TABLE IF EXISTS `gn_golf_round` CASCADE
;

DROP TABLE IF EXISTS `gn_handicap_provider` CASCADE
;

DROP TABLE IF EXISTS `gn_hole_score` CASCADE
;

DROP TABLE IF EXISTS `gn_hp_synch_queue` CASCADE
;

DROP TABLE IF EXISTS `gn_lead_type` CASCADE
;

DROP TABLE IF EXISTS `gn_member_club` CASCADE
;

DROP TABLE IF EXISTS `gn_member_club_migration` CASCADE
;

DROP TABLE IF EXISTS `gn_member_club_type` CASCADE
;

DROP TABLE IF EXISTS `gn_member_club_zip` CASCADE
;

DROP TABLE IF EXISTS `gn_member_status` CASCADE
;

DROP TABLE IF EXISTS `gn_merchant_fee_bill_option` CASCADE
;

DROP TABLE IF EXISTS `gn_merchant_payment` CASCADE
;

DROP TABLE IF EXISTS `gn_merchant_provider` CASCADE
;

DROP TABLE IF EXISTS `gn_merchant_status` CASCADE
;

DROP TABLE IF EXISTS `gn_merchant_synch_queue` CASCADE
;

DROP TABLE IF EXISTS `gn_pay_method_type` CASCADE
;

DROP TABLE IF EXISTS `gn_payment_type` CASCADE
;

DROP TABLE IF EXISTS `gn_renewal_status` CASCADE
;

DROP TABLE IF EXISTS `gn_role_type` CASCADE
;

DROP TABLE IF EXISTS `gn_scoring_type` CASCADE
;

DROP TABLE IF EXISTS `gn_shot_detail` CASCADE
;

DROP TABLE IF EXISTS `gn_subscription` CASCADE
;

DROP TABLE IF EXISTS `gn_subscription_club_filter` CASCADE
;

DROP TABLE IF EXISTS `gn_subscription_fee` CASCADE
;

DROP TABLE IF EXISTS `gn_subscription_fee_map` CASCADE
;

DROP TABLE IF EXISTS `gn_subscription_status` CASCADE
;

DROP TABLE IF EXISTS `gn_subscription_type` CASCADE
;

DROP TABLE IF EXISTS `gn_synch_status` CASCADE
;

DROP TABLE IF EXISTS `gn_tee_rating` CASCADE
;

DROP TABLE IF EXISTS `gn_transaction` CASCADE
;

DROP TABLE IF EXISTS `gn_transaction_status` CASCADE
;

DROP TABLE IF EXISTS `gn_transaction_sub_detail` CASCADE
;

DROP TABLE IF EXISTS `gn_transaction_type` CASCADE
;

DROP TABLE IF EXISTS `gn_user_action_type` CASCADE
;

DROP TABLE IF EXISTS `gn_user_audit` CASCADE
;

/* Create Tables */

CREATE TABLE `gn_address_type`
(
	`address_type_cd` CHAR(20) NOT NULL,
	`address_type_value` VARCHAR(100) NOT NULL,
	CONSTRAINT `PK_AddressType` PRIMARY KEY (`address_type_cd` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_assn_bill_schedule`
(
	`assn_bill_schedule_id` INT NOT NULL AUTO_INCREMENT,
	`association_id` INT NOT NULL,
	`month` INT NOT NULL,
	`day` INT NOT NULL,
	CONSTRAINT `PK_gn_assn_bill_schedule` PRIMARY KEY (`assn_bill_schedule_id` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_assn_billing_settings`
(
	`association_id` INT NOT NULL,
	`billing_enabled` BOOL NOT NULL DEFAULT 1,
	`include_est_merchant_fee` BOOL NOT NULL DEFAULT 0,
	`merchant_fee_bill_cd` CHAR(20) 	 NULL,
	`merchant_fee_pct` DECIMAL(5,2) 	 NULL,
	`apply_deactivation_discount` BOOL NOT NULL DEFAULT 0,
	CONSTRAINT `PK_gn_assn_billing_settings` PRIMARY KEY (`association_id` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_assn_discount_rule`
(
	`assn_discount_rule_id` INT NOT NULL AUTO_INCREMENT,
	`association_id` INT NOT NULL,
	`days_limit` INT NOT NULL,
	`discount_pct` INT NOT NULL,
	CONSTRAINT `PK_gn_assn_discount_rule` PRIMARY KEY (`assn_discount_rule_id` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_association`
(
	`association_id` INT NOT NULL AUTO_INCREMENT,
	`handicap_provider_id` INT NOT NULL,
	`hp_association_num` INT 	 NULL,
	`association_name` VARCHAR(200) NOT NULL,
	`address` VARCHAR(200) 	 NULL,
	`city` VARCHAR(200) 	 NULL,
	`state` CHAR(2) 	 NULL,
	`zip_code` CHAR(10) 	 NULL,
	`gn_coop_member` BOOL NOT NULL,
	`website` VARCHAR(200) 	 NULL,
	`association_phone` VARCHAR(20) 	 NULL,
	`online_join_url` VARCHAR(200) 	 NULL,
	`logo` VARCHAR(200) 	 NULL,
	`mp_association_num` VARCHAR(100) 	 NULL,
	CONSTRAINT `PK_Association` PRIMARY KEY (`association_id` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_association_customer`
(
	`association_id` INT NOT NULL,
	`customer_id` INT NOT NULL,
	`user_name` VARCHAR(100) NOT NULL,
	`password` VARCHAR(100) NOT NULL,
	`assoc_login_type_cd` CHAR(20) NOT NULL,
	CONSTRAINT `PK_AssociationCustomer` PRIMARY KEY (`association_id` ASC, `customer_id` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_association_facility`
(
	`association_id` INT NOT NULL,
	`facility_id` INT NOT NULL,
	CONSTRAINT `PK_gn_association_facility` PRIMARY KEY (`association_id` ASC, `facility_id` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_association_log`
(
	`association_log_id` BIGINT NOT NULL AUTO_INCREMENT,
	`association_id` INT NOT NULL,
	`log_entry_type` CHAR(20) NOT NULL,
	`log_entry` TEXT 	 NULL,
	CONSTRAINT `PK_AssociationLog` PRIMARY KEY (`association_log_id` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_association_login_type`
(
	`assoc_login_type_cd` CHAR(20) NOT NULL,
	`assoc_login_value` VARCHAR(100) NOT NULL,
	CONSTRAINT `PK_AssociationLoginType` PRIMARY KEY (`assoc_login_type_cd` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_association_migration`
(
	`association_id` INT NOT NULL,
	`status` VARCHAR(10) NOT NULL,
	`started_at` TIMESTAMP 	 NULL,
	`message` TEXT 	 NULL,
	CONSTRAINT `PK_gn_association_migration` PRIMARY KEY (`association_id` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_association_settings`
(
	`association_id` INT NOT NULL,
	`display_fee` BOOL NOT NULL,
	`renewal_start` CHAR(5) NOT NULL,
	`apply_golfer_privacy` BOOL NOT NULL,
	`calendar_start` CHAR(5) NOT NULL,
	`set_expiration_dates` BOOL NOT NULL,
	`custom_css` TEXT 	 NULL,
	`google_tracking_script` TEXT 	 NULL,
	`member_name_format` CHAR(10) 	 NULL,
	`default_state` CHAR(2) 	 NULL,
	`force_ssl_on_checkout` BOOL 	 NULL,
	`encrypt_member_number` BOOL 	 NULL,
	`enable_transaction_fee` BOOL 	 NULL,
	`default_transaction_fee` DECIMAL(10,2) 	 NULL,
	`allow_auto_renewal` BOOL 	 NULL,
	`allow_approval_process` BOOL NOT NULL,
	`hide_profile_info` BOOL NOT NULL,
	`hp_provider_offline` BOOL NOT NULL,
	`hp_optional_fields` VARCHAR(200) 	 NULL,
	`hp_username` VARCHAR(100) 	 NULL,
	`hp_password` VARCHAR(100) 	 NULL,
	`allow_limited_membership` BOOL NOT NULL,
	`limited_membership_title` VARCHAR(200) 	 NULL,
	`limited_membership_text` TEXT 	 NULL,
	`merchant_provider_id` INT 	 NULL,
	`mp_merchant_fields` TEXT 	 NULL,
	`mp_username` VARCHAR(100) 	 NULL,
	`mp_password` VARCHAR(100) 	 NULL,
	`allow_snail_mail_opt_in` BOOL 	 NULL,
	`renew_days_before_calendar` INT 	 NULL,
	CONSTRAINT `PK_AssociationSettings` PRIMARY KEY (`association_id` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_association_zip_code`
(
	`association_id` INT NOT NULL,
	`zip_code` CHAR(10) NOT NULL,
	CONSTRAINT `PK_AssociationZipCode` PRIMARY KEY (`association_id` ASC, `zip_code` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_bill_adjustment_type`
(
	`bill_adj_type_cd` CHAR(20) NOT NULL,
	`bill_adj_type_value` VARCHAR(100) NOT NULL,
	CONSTRAINT `PK_gn_bill_adjustment_type` PRIMARY KEY (`bill_adj_type_cd` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_bill_status`
(
	`bill_status_cd` CHAR(20) NOT NULL,
	`bill_status_value` VARCHAR(100) NOT NULL,
	CONSTRAINT `PK_gn_payment_status` PRIMARY KEY (`bill_status_cd` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_calendar_year_type`
(
	`calendar_year_type_cd` CHAR(20) NOT NULL,
	`calendar_year_type_value` VARCHAR(100) NOT NULL,
	CONSTRAINT `PK_gn_calendar_year_type` PRIMARY KEY (`calendar_year_type_cd` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_club_bill`
(
	`club_bill_id` INT NOT NULL AUTO_INCREMENT,
	`club_service_id` INT NOT NULL,
	`start_bill_date` DATE NOT NULL,
	`end_bill_date` DATE NOT NULL,
	`bill_number` VARCHAR(20) NOT NULL,
	`previous_balance` DECIMAL(10,2) NOT NULL,
	`payments_received` DECIMAL(10,2) NOT NULL,
	`payments_to_club` DECIMAL(10,2) NOT NULL,
	`transaction_refunds` DECIMAL(10,2) NOT NULL,
	`bill_amount` DECIMAL(10,2) NOT NULL,
	`amount_due` DECIMAL(10,2) NOT NULL,
	`bill_status_cd` CHAR(20) NOT NULL,
	CONSTRAINT `PK_gn_club_bill` PRIMARY KEY (`club_bill_id` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_club_bill_adjustment`
(
	`club_bill_adj_id` INT NOT NULL AUTO_INCREMENT,
	`club_service_id` INT NOT NULL,
	`bill_adj_type_cd` CHAR(20) NOT NULL,
	`adj_date` DATE NOT NULL,
	`adj_description` VARCHAR(200) NOT NULL,
	`adj_amount` DECIMAL(10,2) NOT NULL,
	`applied_to_payment` BOOL NOT NULL DEFAULT 0,
	`club_bill_id` INT 	 NULL,
	`applied_to_bill` BOOL NOT NULL DEFAULT 0,
	CONSTRAINT `PK_gn_club_bill_adjustment` PRIMARY KEY (`club_bill_adj_id` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_club_contact_type`
(
	`contact_type_cd` CHAR(20) NOT NULL,
	`contact_type_value` VARCHAR(100) NOT NULL,
	CONSTRAINT `PK_club_contact_type` PRIMARY KEY (`contact_type_cd` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_club_customer_field`
(
	`club_customer_id` INT NOT NULL,
	`field_name` VARCHAR(100) NOT NULL,
	`field_value` VARCHAR(100) NOT NULL,
	CONSTRAINT `PK_gn_club_customer_field` PRIMARY KEY (`club_customer_id` ASC, `field_name` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_club_field`
(
	`club_service_id` INT NOT NULL,
	`field_name` VARCHAR(100) NOT NULL,
	`is_required` BOOL NOT NULL,
	`display_order` SMALLINT 	 NULL,
	CONSTRAINT `PK_gn_club_fields` PRIMARY KEY (`club_service_id` ASC, `field_name` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_club_payment`
(
	`club_payment_id` INT NOT NULL AUTO_INCREMENT,
	`club_service_id` INT NOT NULL,
	`payment_date` DATE NOT NULL,
	`payment_type_cd` CHAR(20) NOT NULL,
	`payment_amount` DECIMAL(10,2) NOT NULL,
	`merchant_payment_id` INT 	 NULL,
	`club_bill_adj_id` INT 	 NULL,
	`club_bill_id` INT 	 NULL,
	`applied_to_bill` BOOL NOT NULL DEFAULT 0,
	CONSTRAINT `PK_gn_club_payment` PRIMARY KEY (`club_payment_id` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_club_payment_check`
(
	`club_payment_check_id` INT NOT NULL AUTO_INCREMENT,
	`club_payment_id` INT NOT NULL,
	`check_number` VARCHAR(20) 	 NULL,
	`check_amount` DECIMAL(10,2) NOT NULL,
	`check_memo` VARCHAR(100) 	 NULL,
	CONSTRAINT `PK_gn_club_payment_check` PRIMARY KEY (`club_payment_check_id` ASC)
)
ENGINE=INNODB

;

CREATE TABLE `gn_club_payment_detail`
(
	`club_payment_detail_id` INT NOT NULL AUTO_INCREMENT,
	`club_payment_id` INT NOT NULL,
	`club_bill_adj_id` INT 	 NULL,
	`transaction_id` INT 	 NULL,
	`is_postponed` BOOL NOT NULL,
	`is_deactivated` BOOL NOT NULL,
	`deactivation_discount_amt` DECIMAL(10,2) 	 NULL,
	CONSTRAINT `PK_gn_club_payment_detail` PRIMARY KEY (`club_payment_detail_id` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_club_service`
(
	`club_service_id` INT NOT NULL AUTO_INCREMENT,
	`club_id` INT NOT NULL,
	`hp_service_num` INT 	 NULL,
	`club_service_name` VARCHAR(200) 	 NULL,
	`club_service_email` VARCHAR(200) 	 NULL,
	`club_service_phone` VARCHAR(20) 	 NULL,
	`club_service_description` TEXT 	 NULL,
	`gender_type_cd` CHAR(10) 	 NULL,
	`club_service_contact` VARCHAR(200) 	 NULL,
	`is_default` BOOL NOT NULL,
	`is_active` BOOL NOT NULL,
	`address1` VARCHAR(200) 	 NULL,
	`address2` VARCHAR(200) 	 NULL,
	`city` VARCHAR(200) 	 NULL,
	`state` CHAR(2) 	 NULL,
	`zip_code` CHAR(10) 	 NULL,
	`longitude` DECIMAL(10,6) 	 NULL,
	`latitude` DECIMAL(10,6) 	 NULL,
	`last_amount_due` DECIMAL(10,2) 	 NULL,
	`last_bill_date` DATE 	 NULL,
	`next_bill_date` DATE 	 NULL,
	`next_bill_number_seq` INT 	 NULL,
	CONSTRAINT `PK_gn_member_club_service` PRIMARY KEY (`club_service_id` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_club_service_contact`
(
	`club_service_id` INT NOT NULL,
	`customer_id` INT NOT NULL,
	`contact_type_cd` CHAR(20) NOT NULL,
	CONSTRAINT `PK_gn_club_service_contact` PRIMARY KEY (`club_service_id` ASC, `customer_id` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_club_service_customer`
(
	`club_customer_id` INT NOT NULL AUTO_INCREMENT,
	`club_service_id` INT NOT NULL,
	`customer_id` INT NOT NULL,
	`member_status_cd` CHAR(20) NOT NULL,
	`start_date` DATE NOT NULL,
	`end_date` DATE 	 NULL,
	`hp_customer_num` INT 	 NULL,
	`hp_inactivation_date` DATE 	 NULL,
	`hp_status_datetime` DATETIME 	 NULL,
	`hp_revision_datetime` DATETIME 	 NULL,
	`hp_paid_datetime` DATETIME 	 NULL,
	`hp_member_type` CHAR(10) 	 NULL,
	CONSTRAINT `PK_gn_member_club_customer` PRIMARY KEY (`club_customer_id` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_club_service_settings`
(
	`club_service_id` INT NOT NULL COMMENT ' ',
	`nmi_token` VARCHAR(50) 	 NULL,
	`bank_name` VARCHAR(200) 	 NULL,
	`ach_routing_number` VARCHAR(20) 	 NULL,
	`ach_bank_number` VARCHAR(50) 	 NULL,
	`auto_renew` BOOL NOT NULL,
	`transaction_fee` DECIMAL(10,2) 	 NULL,
	`billing_active` BOOL NOT NULL,
	`calendar_year_type_cd` CHAR(20) 	 NULL,
	`apply_rollover` BOOL 	 NULL,
	`subscription_term_cd` CHAR(20) 	 NULL,
	`accounting_macro_id` VARCHAR(50) 	 NULL,
	`hp_optional_fields` VARCHAR(200) 	 NULL,
	`use_snail_mail` BOOL NOT NULL,
	CONSTRAINT `PK_gn_club_service_settings` PRIMARY KEY (`club_service_id` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_contact_type`
(
	`contact_type_cd` CHAR(20) NOT NULL,
	`contact_type_value` VARCHAR(100) NOT NULL,
	CONSTRAINT `PK_ContactType` PRIMARY KEY (`contact_type_cd` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_course`
(
	`course_id` INT NOT NULL AUTO_INCREMENT,
	`facility_id` INT NOT NULL,
	`course_name` VARCHAR(200) NOT NULL,
	`address` VARCHAR(200) 	 NULL,
	`city` VARCHAR(200) 	 NULL,
	`state` CHAR(2) 	 NULL,
	`zip_code` CHAR(10) 	 NULL,
	`longitude` DECIMAL(10,6) 	 NULL,
	`latitude` DECIMAL(10,6) 	 NULL,
	CONSTRAINT `PK_gn_course` PRIMARY KEY (`course_id` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_course_customer_link`
(
	`course_id` INT NOT NULL,
	`customer_id` INT NOT NULL,
	`course_link_type_cd` CHAR(20) NOT NULL,
	CONSTRAINT `PK_gn_course_customer_link` PRIMARY KEY (`course_id` ASC, `customer_id` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_course_hole`
(
	`course_hole_id` INT NOT NULL AUTO_INCREMENT,
	`course_id` INT NOT NULL,
	`hole_number` SMALLINT NOT NULL,
	`par` SMALLINT NOT NULL,
	`longitude` DECIMAL(10,2) 	 NULL,
	`latitude` DECIMAL(10,2) 	 NULL,
	CONSTRAINT `PK_gn_course_hole` PRIMARY KEY (`course_hole_id` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_course_link_type`
(
	`course_link_type_cd` CHAR(20) NOT NULL,
	`course_link_type_value` VARCHAR(100) NOT NULL,
	CONSTRAINT `PK_gn_course_link_type` PRIMARY KEY (`course_link_type_cd` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_course_score`
(
	`course_score_id` INT NOT NULL AUTO_INCREMENT,
	`course_id` INT NOT NULL,
	`customer_id` INT NOT NULL,
	`golf_round_id` INT 	 NULL,
	`course_tee_id` INT 	 NULL,
	`score` SMALLINT 	 NULL,
	CONSTRAINT `PK_gn_course_score` PRIMARY KEY (`course_score_id` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_course_tee`
(
	`course_tee_id` INT NOT NULL AUTO_INCREMENT,
	`course_id` INT NOT NULL,
	`tee_name` VARCHAR(200) NOT NULL,
	`tee_rating_cd` CHAR(20) NOT NULL,
	`yardage` INT 	 NULL,
	`slope_rating` INT 	 NULL,
	`usga_rating` DECIMAL(10,2) 	 NULL,
	`par` SMALLINT 	 NULL,
	CONSTRAINT `PK_gn_course_tee` PRIMARY KEY (`course_tee_id` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_customer`
(
	`customer_id` INT NOT NULL AUTO_INCREMENT,
	`prefix` VARCHAR(50) 	 NULL,
	`first_name` VARCHAR(100) NOT NULL,
	`middle_name` VARCHAR(100) 	 NULL,
	`last_name` VARCHAR(50) NOT NULL,
	`suffix` VARCHAR(50) 	 NULL,
	`email` VARCHAR(200) 	 NULL,
	`gender` CHAR(1) 	 NULL,
	`date_of_birth` DATE 	 NULL,
	`handicap` SMALLINT 	 NULL,
	`average_score` DECIMAL(5,2) 	 NULL,
	`is_user` BOOL 	 NULL,
	CONSTRAINT `PK_Customer` PRIMARY KEY (`customer_id` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_customer_address`
(
	`customer_id` INT NOT NULL,
	`address_type_cd` CHAR(20) NOT NULL,
	`address1` VARCHAR(200) 	 NULL,
	`address2` VARCHAR(200) 	 NULL,
	`city` VARCHAR(200) 	 NULL,
	`state` CHAR(2) 	 NULL,
	`zip_code` CHAR(10) 	 NULL,
	`longitude` DECIMAL(10,6) 	 NULL,
	`latitude` DECIMAL(10,6) 	 NULL,
	CONSTRAINT `PK_CustomerAddress` PRIMARY KEY (`customer_id` ASC, `address_type_cd` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_customer_contact`
(
	`customer_id` INT NOT NULL,
	`contact_type_cd` CHAR(20) NOT NULL,
	`contact_value` VARCHAR(200) NOT NULL,
	CONSTRAINT `PK_CustomerContact` PRIMARY KEY (`customer_id` ASC, `contact_type_cd` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_customer_golf_clubs`
(
	`customer_id` INT NOT NULL,
	`golf_club_type_cd` CHAR(20) NOT NULL,
	`distance` INT 	 NULL,
	CONSTRAINT `PK_gn_customer_clubs` PRIMARY KEY (`customer_id` ASC, `golf_club_type_cd` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_customer_lead_status`
(
	`customer_lead_id` INT NOT NULL,
	`customer_id` INT NOT NULL,
	`lead_type_cd` CHAR(20) NOT NULL,
	CONSTRAINT `PK_CustomerLeadStatus` PRIMARY KEY (`customer_lead_id` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_customer_link`
(
	`customer_id` INT NOT NULL,
	`linked_customer_id` INT NOT NULL,
	`customer_link_type_cd` CHAR(20) NOT NULL,
	CONSTRAINT `PK_CustomerLink` PRIMARY KEY (`customer_id` ASC, `linked_customer_id` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_customer_link_type`
(
	`customer_link_type_cd` CHAR(20) NOT NULL,
	`customer_link_value` VARCHAR(100) NOT NULL,
	CONSTRAINT `PK_CustomerLinkType` PRIMARY KEY (`customer_link_type_cd` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_customer_pay_method`
(
	`customer_pay_method_id` INT NOT NULL AUTO_INCREMENT,
	`customer_id` INT NOT NULL,
	`pay_method_type_cd` CHAR(20) NOT NULL,
	`merchant_token` VARCHAR(50) NOT NULL,
	`masked_pay_number` VARCHAR(50) NOT NULL,
	`pay_method_nickname` VARCHAR(100) 	 NULL,
	CONSTRAINT `PK_gn_customer_pay_method` PRIMARY KEY (`customer_pay_method_id` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_customer_role`
(
	`customer_role_id` INT NOT NULL AUTO_INCREMENT,
	`customer_id` INT NOT NULL,
	`role_type_cd` CHAR(20) NOT NULL,
	CONSTRAINT `PK_CustomerRole` PRIMARY KEY (`customer_role_id` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_email_template`
(
	`email_template_cd` CHAR(20) NOT NULL,
	`association_id` INT NOT NULL,
	`email_subject` VARCHAR(500) 	 NULL,
	`email_body` TEXT 	 NULL,
	CONSTRAINT `PK_EmailTemplate` PRIMARY KEY (`email_template_cd` ASC, `association_id` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_facility`
(
	`facility_id` INT NOT NULL AUTO_INCREMENT,
	`handicap_provider_id` INT NOT NULL,
	`facility_name` VARCHAR(200) NOT NULL,
	`hp_facility_num` VARCHAR(50) NOT NULL,
	`facility_type_cd` CHAR(20) NOT NULL,
	`address` VARCHAR(200) 	 NULL,
	`city` VARCHAR(200) 	 NULL,
	`state` CHAR(2) 	 NULL,
	`zip_code` CHAR(10) 	 NULL,
	`longitude` DECIMAL(10,6) 	 NULL,
	`latitude` DECIMAL(10,6) 	 NULL,
	CONSTRAINT `PK_gn_facility` PRIMARY KEY (`facility_id` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_facility_type`
(
	`facility_type_cd` CHAR(20) NOT NULL,
	`facility_type_value` VARCHAR(100) NOT NULL,
	CONSTRAINT `PK_gn_facility_type` PRIMARY KEY (`facility_type_cd` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_fee_level`
(
	`fee_level_cd` CHAR(20) NOT NULL,
	`fee_level_value` VARCHAR(100) 	 NULL,
	CONSTRAINT `PK_gn_subscription_level` PRIMARY KEY (`fee_level_cd` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_fee_type`
(
	`fee_type_cd` CHAR(20) NOT NULL,
	`fee_type_value` VARCHAR(100) NOT NULL,
	CONSTRAINT `PK_gn_fee_type_cd` PRIMARY KEY (`fee_type_cd` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_gender_type`
(
	`gender_type_cd` CHAR(10) NOT NULL,
	`gender_value` VARCHAR(100) NOT NULL,
	CONSTRAINT `PK_GenderType` PRIMARY KEY (`gender_type_cd` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_golf_club_type`
(
	`golf_club_type_cd` CHAR(20) NOT NULL,
	`golf_club_type_value` VARCHAR(100) 	 NULL,
	`default_distance` SMALLINT 	 NULL,
	CONSTRAINT `PK_gn_club_type` PRIMARY KEY (`golf_club_type_cd` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_golf_round`
(
	`golf_round_id` INT NOT NULL AUTO_INCREMENT,
	`course_id` INT NOT NULL,
	`scoring_type_cd` CHAR(20) NOT NULL,
	`start_datetime` DATETIME NOT NULL,
	`end_datetime` DATETIME 	 NULL,
	CONSTRAINT `PK_gn_golf_round` PRIMARY KEY (`golf_round_id` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_handicap_provider`
(
	`handicap_provider_id` INT NOT NULL AUTO_INCREMENT,
	`handicap_provider_name` VARCHAR(200) NOT NULL,
	CONSTRAINT `PK_HandicapProvider` PRIMARY KEY (`handicap_provider_id` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_hole_score`
(
	`hole_score_id` INT NOT NULL AUTO_INCREMENT,
	`course_score_id` INT NOT NULL,
	`course_hole_id` INT NOT NULL,
	`score` SMALLINT NOT NULL,
	CONSTRAINT `PK_gn_hole_score` PRIMARY KEY (`hole_score_id` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_hp_synch_queue`
(
	`hp_synch_id` INT NOT NULL AUTO_INCREMENT,
	`club_customer_id` INT NOT NULL,
	`queue_add_datetime` DATETIME NOT NULL,
	`status_datetime` DATETIME NOT NULL,
	`synch_status_cd` CHAR(20) NOT NULL,
	CONSTRAINT `PK_gn_hp_synch_queue` PRIMARY KEY (`hp_synch_id` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_lead_type`
(
	`lead_type_cd` CHAR(20) NOT NULL,
	`lead_type_value` VARCHAR(100) NOT NULL,
	CONSTRAINT `PK_LeadType` PRIMARY KEY (`lead_type_cd` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_member_club`
(
	`club_id` INT NOT NULL AUTO_INCREMENT,
	`association_id` INT NOT NULL,
	`hp_club_num` INT 	 NULL,
	`club_name` VARCHAR(200) NOT NULL,
	`member_club_type_cd` CHAR(20) 	 NULL,
	`display_in_directory` BOOL NOT NULL,
	`club_description` TEXT 	 NULL,
	`club_contact` VARCHAR(200) 	 NULL,
	`club_email` VARCHAR(200) 	 NULL,
	`club_phone` VARCHAR(20) 	 NULL,
	CONSTRAINT `PK_gn_member_club` PRIMARY KEY (`club_id` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_member_club_migration`
(
	`club_id` INT NOT NULL,
	`status` VARCHAR(10) NOT NULL,
	`started_at` TIMESTAMP 	 NULL,
	`message` TEXT 	 NULL,
	CONSTRAINT `PK_gn_member_club_migration` PRIMARY KEY (`club_id` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_member_club_type`
(
	`member_club_type_cd` CHAR(20) NOT NULL,
	`member_club_type_value` VARCHAR(100) NOT NULL,
	CONSTRAINT `PK_gn_club_type` PRIMARY KEY (`member_club_type_cd` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_member_club_zip`
(
	`club_id` INT NOT NULL,
	`zip_code` CHAR(10) NOT NULL,
	CONSTRAINT `PK_gn_member_club_zip` PRIMARY KEY (`club_id` ASC, `zip_code` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_member_status`
(
	`member_status_cd` CHAR(20) NOT NULL,
	`member_status_value` VARCHAR(200) NOT NULL,
	CONSTRAINT `PK_gn_member_status` PRIMARY KEY (`member_status_cd` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_merchant_fee_bill_option`
(
	`merchant_fee_bill_cd` CHAR(20) NOT NULL,
	`merchant_fee_bill_option` VARCHAR(100) NOT NULL,
	CONSTRAINT `PK_gn_merchant_fee_bill_option` PRIMARY KEY (`merchant_fee_bill_cd` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_merchant_payment`
(
	`merchant_payment_id` INT NOT NULL AUTO_INCREMENT,
	`merchant_provider_id` INT NOT NULL,
	`merchant_number` VARCHAR(50) 	 NULL,
	`payment_datetime` DATETIME NOT NULL,
	`transaction_token` VARCHAR(50) 	 NULL,
	`payment_amount` DECIMAL(10,2) NOT NULL,
	`merchant_status_cd` CHAR(20) NOT NULL,
	CONSTRAINT `PK_gn_merchant_payment` PRIMARY KEY (`merchant_payment_id` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_merchant_provider`
(
	`merchant_provider_id` INT NOT NULL AUTO_INCREMENT,
	`merchant_provider_name` VARCHAR(200) NOT NULL,
	CONSTRAINT `PK_gn_merchant_provider` PRIMARY KEY (`merchant_provider_id` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_merchant_status`
(
	`merchant_status_cd` CHAR(20) NOT NULL,
	`merchant_status_value` VARCHAR(100) NOT NULL,
	CONSTRAINT `PK_gn_merchant_payment_status` PRIMARY KEY (`merchant_status_cd` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_merchant_synch_queue`
(
	`merchant_synch_id` INT NOT NULL AUTO_INCREMENT,
	`merchant_payment_id` INT NOT NULL,
	`queue_add_datetime` DATETIME NOT NULL,
	`status_datetime` DATETIME NOT NULL,
	`synch_status_cd` CHAR(20) NOT NULL,
	CONSTRAINT `PK_gn_merchant_synch_queue` PRIMARY KEY (`merchant_synch_id` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_pay_method_type`
(
	`pay_method_type_cd` CHAR(20) NOT NULL,
	`pay_method_type_value` VARCHAR(100) NOT NULL,
	CONSTRAINT `PK_gn_pay_method_type` PRIMARY KEY (`pay_method_type_cd` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_payment_type`
(
	`payment_type_cd` CHAR(20) NOT NULL,
	`payment_type_value` VARCHAR(100) 	 NULL,
	CONSTRAINT `PK_gn_payment_type` PRIMARY KEY (`payment_type_cd` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_renewal_status`
(
	`renewal_status_cd` CHAR(20) NOT NULL,
	`renewal_status_value` VARCHAR(100) NOT NULL,
	CONSTRAINT `PK_gn_renewal_status` PRIMARY KEY (`renewal_status_cd` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_role_type`
(
	`role_type_cd` CHAR(20) NOT NULL,
	`role_type_value` VARCHAR(100) NOT NULL,
	CONSTRAINT `PK_RoleType` PRIMARY KEY (`role_type_cd` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_scoring_type`
(
	`scoring_type_cd` CHAR(20) NOT NULL,
	`scoring_type_value` VARCHAR(100) NOT NULL,
	CONSTRAINT `PK_gn_scoring_type` PRIMARY KEY (`scoring_type_cd` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_shot_detail`
(
	`hole_score_id` INT NOT NULL,
	`shot_number` SMALLINT NOT NULL,
	`golf_club_type_cd` CHAR(20) NOT NULL,
	`longitude` DECIMAL(10,2) 	 NULL,
	`latitude` DECIMAL(10,2) 	 NULL,
	`distance` DECIMAL(10,2) 	 NULL,
	`last_shot` BOOL NOT NULL,
	CONSTRAINT `PK_gn_shot_detail` PRIMARY KEY (`hole_score_id` ASC, `shot_number` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_subscription`
(
	`subscription_id` INT NOT NULL AUTO_INCREMENT,
	`club_customer_id` INT NOT NULL,
	`subscription_type_id` INT NOT NULL,
	`subscription_status_cd` CHAR(20) NOT NULL,
	`status_reason` VARCHAR(200) 	 NULL,
	`start_date` DATE NOT NULL,
	`end_date` DATE NOT NULL,
	`auto_renew` BOOL NOT NULL,
	`auto_renewal_date` DATE 	 NULL,
	`renewal_status_cd` CHAR(20) 	 NULL,
	CONSTRAINT `PK_gn_subscription` PRIMARY KEY (`subscription_id` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_subscription_club_filter`
(
	`subscription_fee_id` INT NOT NULL,
	`club_service_id` INT NOT NULL,
	`apply_fee_override` BOOL NOT NULL,
	`fee_override` DECIMAL(10,2) 	 NULL,
	CONSTRAINT `PK_gn_subscription_club_filter` PRIMARY KEY (`subscription_fee_id` ASC, `club_service_id` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_subscription_fee`
(
	`subscription_fee_id` INT NOT NULL AUTO_INCREMENT,
	`association_id` INT NOT NULL,
	`fee_level_cd` CHAR(20) NOT NULL,
	`fee_type_cd` CHAR(20) NOT NULL,
	`fee_name` VARCHAR(200) NOT NULL,
	`fee_amount` DECIMAL(10,2) NOT NULL,
	`fee_description` TEXT 	 NULL,
	`start_date` DATE 	 NULL,
	`end_date` DATE 	 NULL,
	`transaction_type_cd` CHAR(20) 	 NULL,
	`gender_type_cd` CHAR(10) 	 NULL,
	`online_only` BOOL NOT NULL,
	`low_age` SMALLINT 	 NULL,
	`high_age` SMALLINT 	 NULL,
	`requires_promotion` BOOL NOT NULL,
	`promotion_code` VARCHAR(100) 	 NULL,
	`display_order` INT 	 NULL,
	`exclude_inactive` BOOL NOT NULL,
	CONSTRAINT `PK_gn_subscription_type` PRIMARY KEY (`subscription_fee_id` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_subscription_fee_map`
(
	`subscription_type_id` INT NOT NULL,
	`subscription_fee_id` INT NOT NULL,
	CONSTRAINT `PK_gn_membership_subscription` PRIMARY KEY (`subscription_type_id` ASC, `subscription_fee_id` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_subscription_status`
(
	`subscription_status_cd` CHAR(20) NOT NULL,
	`subscription_status_value` VARCHAR(100) NOT NULL,
	`requires_reason` BOOL NOT NULL,
	CONSTRAINT `PK_gn_subscription_status` PRIMARY KEY (`subscription_status_cd` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_subscription_type`
(
	`subscription_type_id` INT NOT NULL AUTO_INCREMENT,
	`club_service_id` INT NOT NULL,
	`subscription_type_name` VARCHAR(200) NOT NULL,
	`is_default` BOOL NOT NULL,
	`requires_approval` BOOL NOT NULL,
	`auto_reject_days` SMALLINT 	 NULL,
	`allow_auto_renew` BOOL NOT NULL,
	`auto_renew_days` SMALLINT 	 NULL,
	`renew_subscription_type_id` INT 	 NULL,
	`is_limited_membership` BOOL NOT NULL,
	`notify_email` VARCHAR(200) 	 NULL,
	`is_archived` BOOL NOT NULL,
	CONSTRAINT `PK_gn_membership_type` PRIMARY KEY (`subscription_type_id` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_synch_status`
(
	`synch_status_cd` CHAR(20) NOT NULL,
	`synch_status_value` VARCHAR(100) NOT NULL,
	CONSTRAINT `PK_gn_synch_status` PRIMARY KEY (`synch_status_cd` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_tee_rating`
(
	`tee_rating_cd` CHAR(20) NOT NULL,
	`tee_rating_value` VARCHAR(100) NOT NULL,
	CONSTRAINT `PK_gn_tee_rating` PRIMARY KEY (`tee_rating_cd` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_transaction`
(
	`transaction_id` INT NOT NULL AUTO_INCREMENT,
	`subscription_id` INT NOT NULL,
	`transaction_date` DATE NOT NULL,
	`transaction_type_cd` CHAR(20) NOT NULL,
	`transaction_status_cd` CHAR(20) NOT NULL,
	`transaction_amount` DECIMAL(10,2) NOT NULL,
	`association_amount` DECIMAL(10,2) NOT NULL,
	`club_amount` DECIMAL(10,2) NOT NULL,
	`transaction_fee` DECIMAL(10,2) 	 NULL,
	`merchant_payment_id` INT 	 NULL,
	`original_transaction_id` INT 	 NULL,
	`access_key` VARCHAR(50) 	 NULL,
	`applied_to_payment` BOOL NOT NULL DEFAULT 0,
	`club_bill_id` INT 	 NULL,
	`applied_to_bill` BOOL NOT NULL DEFAULT 0,
	`club_bill_adj_id` INT 	 NULL,
	`includes_adjustment` BOOL NOT NULL DEFAULT 0,
	`paid_online` BOOL NOT NULL DEFAULT 1,
	CONSTRAINT `PK_gn_transaction` PRIMARY KEY (`transaction_id` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_transaction_status`
(
	`transaction_status_cd` CHAR(20) NOT NULL,
	`transaction_status_value` VARCHAR(100) NOT NULL,
	CONSTRAINT `PK_gn_transaction_status` PRIMARY KEY (`transaction_status_cd` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_transaction_sub_detail`
(
	`transaction_id` INT NOT NULL,
	`subscription_fee_id` INT NOT NULL,
	`detail_amount` DECIMAL(10,2) NOT NULL,
	`fee_name` VARCHAR(200) 	 NULL,
	CONSTRAINT `PK_gn_transaction_sub_detail` PRIMARY KEY (`transaction_id` ASC, `subscription_fee_id` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_transaction_type`
(
	`transaction_type_cd` CHAR(20) NOT NULL,
	`transaction_type_value` VARCHAR(100) NOT NULL,
	`is_online` BOOL NOT NULL,
	`is_renew` BOOL NOT NULL,
	CONSTRAINT `PK_gn_transaction_type` PRIMARY KEY (`transaction_type_cd` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_user_action_type`
(
	`user_action_cd` VARCHAR(20) NOT NULL,
	`user_action_value` VARCHAR(100) NOT NULL,
	CONSTRAINT `PK_gn_user_action_type` PRIMARY KEY (`user_action_cd` ASC)
)
ENGINE=InnoDB

;

CREATE TABLE `gn_user_audit`
(
	`user_audit_id` INT NOT NULL AUTO_INCREMENT,
	`customer_id` INT NOT NULL,
	`audit_datetime` DATETIME NOT NULL,
	`user_action_cd` VARCHAR(20) NOT NULL,
	`table_name` VARCHAR(250) NOT NULL,
	`table_pk` INT NOT NULL,
	CONSTRAINT `PK_gn_user_audit` PRIMARY KEY (`user_audit_id` ASC)
)
ENGINE=InnoDB

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `gn_association` 
 ADD INDEX `IXFK_association_handicap_provider` (`handicap_provider_id` ASC)
;

ALTER TABLE `gn_association_customer` 
 ADD INDEX `IXFK_association_customer_association` (`association_id` ASC)
;

ALTER TABLE `gn_association_customer` 
 ADD INDEX `IXFK_association_customer_association_login_type` (`assoc_login_type_cd` ASC)
;

ALTER TABLE `gn_association_customer` 
 ADD INDEX `IXFK_association_customer_customer` (`customer_id` ASC)
;

ALTER TABLE `gn_association_facility` 
 ADD INDEX `IXFK_gn_association_facility_gn_association` (`association_id` ASC)
;

ALTER TABLE `gn_association_facility` 
 ADD INDEX `IXFK_gn_association_facility_gn_facility` (`facility_id` ASC)
;

ALTER TABLE `gn_association_log` 
 ADD INDEX `IXFK_association_log_association` (`association_id` ASC)
;

ALTER TABLE `gn_association_settings` 
 ADD INDEX `IXFK_association_settings_association` (`association_id` ASC)
;

ALTER TABLE `gn_association_settings` 
 ADD INDEX `IXFK_gn_association_settings_gn_merchant_provider` (`merchant_provider_id` ASC)
;

ALTER TABLE `gn_association_zip_code` 
 ADD INDEX `IXFK_association_zip_code_association` (`association_id` ASC)
;

ALTER TABLE `gn_club_bill` 
 ADD INDEX `IXFK_gn_club_bill_gn_club_service` (`club_service_id` ASC)
;

ALTER TABLE `gn_club_bill` 
 ADD INDEX `IXFK_gn_club_bill_gn_payment_status` (`bill_status_cd` ASC)
;

ALTER TABLE `gn_club_bill_adjustment` 
 ADD INDEX `IXFK_gn_club_bill_adjustment_gn_bill_adjustment_type` (`bill_adj_type_cd` ASC)
;

ALTER TABLE `gn_club_bill_adjustment` 
 ADD INDEX `IXFK_gn_club_bill_adjustment_gn_club_service` (`club_service_id` ASC)
;

ALTER TABLE `gn_club_field` 
 ADD INDEX `IXFK_gn_club_fields_gn_club_service` (`club_service_id` ASC)
;

ALTER TABLE `gn_club_payment` 
 ADD INDEX `IXFK_gn_club_payment_gn_club_service` (`club_service_id` ASC)
;

ALTER TABLE `gn_club_payment` 
 ADD INDEX `IXFK_gn_club_payment_gn_merchant_payment` (`merchant_payment_id` ASC)
;

ALTER TABLE `gn_club_payment` 
 ADD INDEX `IXFK_gn_club_payment_gn_payment_type` (`payment_type_cd` ASC)
;

ALTER TABLE `gn_club_payment_detail` 
 ADD INDEX `IXFK_gn_club_payment_detail_gn_club_bill_adjustment` (`club_bill_adj_id` ASC)
;

ALTER TABLE `gn_club_payment_detail` 
 ADD INDEX `IXFK_gn_club_payment_detail_gn_club_payment` (`club_payment_id` ASC)
;

ALTER TABLE `gn_club_payment_detail` 
 ADD INDEX `IXFK_gn_club_payment_detail_gn_transaction` (`transaction_id` ASC)
;

ALTER TABLE `gn_club_service` 
 ADD INDEX `IXFK_gn_club_service_gn_gender_type` (`gender_type_cd` ASC)
;

ALTER TABLE `gn_club_service` 
 ADD INDEX `IXFK_gn_club_service_gn_member_club` (`club_id` ASC)
;

ALTER TABLE `gn_club_service_contact` 
 ADD INDEX `IXFK_gn_club_service_contact_gn_club_service` (`club_service_id` ASC)
;

ALTER TABLE `gn_club_service_contact` 
 ADD INDEX `IXFK_gn_club_service_contact_gn_contact_type` (`contact_type_cd` ASC)
;

ALTER TABLE `gn_club_service_contact` 
 ADD INDEX `IXFK_gn_club_service_contact_gn_customer` (`customer_id` ASC)
;

ALTER TABLE `gn_club_service_customer` 
 ADD INDEX `IXFK_gn_member_club_customer_gn_customer` (`customer_id` ASC)
;

ALTER TABLE `gn_club_service_customer` 
 ADD INDEX `IXFK_gn_member_club_customer_gn_member_status` (`member_status_cd` ASC)
;

ALTER TABLE `gn_club_service_customer` 
 ADD INDEX `IXFK_gn_member_club_service_customer_gn_member_club_service` (`club_service_id` ASC)
;

ALTER TABLE `gn_club_service_customer` 
 ADD INDEX `IX_hp_customer_num` (`hp_customer_num` ASC)
;

ALTER TABLE `gn_club_service_settings` 
 ADD INDEX `IXFK_gn_club_service_settings_gn_calendar_year_type` (`calendar_year_type_cd` ASC)
;

ALTER TABLE `gn_club_service_settings` 
 ADD INDEX `IXFK_gn_club_service_settings_gn_club_service` (`club_service_id` ASC)
;

ALTER TABLE `gn_course` 
 ADD INDEX `IXFK_gn_course_gn_facility` (`facility_id` ASC)
;

ALTER TABLE `gn_course_customer_link` 
 ADD INDEX `IXFK_gn_course_customer_link_gn_course` (`course_id` ASC)
;

ALTER TABLE `gn_course_customer_link` 
 ADD INDEX `IXFK_gn_course_customer_link_gn_course_link_type` (`course_link_type_cd` ASC)
;

ALTER TABLE `gn_course_customer_link` 
 ADD INDEX `IXFK_gn_course_customer_link_gn_customer` (`customer_id` ASC)
;

ALTER TABLE `gn_course_hole` 
 ADD INDEX `IXFK_gn_course_hole_gn_course` (`course_id` ASC)
;

ALTER TABLE `gn_course_score` 
 ADD INDEX `IXFK_gn_course_score_gn_course` (`course_id` ASC)
;

ALTER TABLE `gn_course_score` 
 ADD INDEX `IXFK_gn_course_score_gn_course_tee` (`course_tee_id` ASC)
;

ALTER TABLE `gn_course_score` 
 ADD INDEX `IXFK_gn_course_score_gn_customer` (`customer_id` ASC)
;

ALTER TABLE `gn_course_score` 
 ADD INDEX `IXFK_gn_course_score_gn_golf_round` (`golf_round_id` ASC)
;

ALTER TABLE `gn_course_tee` 
 ADD INDEX `IXFK_gn_course_tee_gn_course` (`course_id` ASC)
;

ALTER TABLE `gn_course_tee` 
 ADD INDEX `IXFK_gn_course_tee_gn_tee_rating` (`tee_rating_cd` ASC)
;

ALTER TABLE `gn_customer_address` 
 ADD INDEX `IXFK_CustomerAddress_AddressType` (`address_type_cd` ASC)
;

ALTER TABLE `gn_customer_address` 
 ADD INDEX `IXFK_CustomerAddress_gn_customer` (`customer_id` ASC)
;

ALTER TABLE `gn_customer_contact` 
 ADD INDEX `IXFK_CustomerContact_ContactType` (`contact_type_cd` ASC)
;

ALTER TABLE `gn_customer_contact` 
 ADD INDEX `IXFK_CustomerContact_gn_customer` (`customer_id` ASC)
;

ALTER TABLE `gn_customer_golf_clubs` 
 ADD INDEX `IXFK_gn_customer_clubs_gn_club_type` (`golf_club_type_cd` ASC)
;

ALTER TABLE `gn_customer_golf_clubs` 
 ADD INDEX `IXFK_gn_customer_clubs_gn_customer` (`customer_id` ASC)
;

ALTER TABLE `gn_customer_lead_status` 
 ADD INDEX `IXFK_CustomerLeadStatus_gn_customer` (`customer_id` ASC)
;

ALTER TABLE `gn_customer_lead_status` 
 ADD INDEX `IXFK_CustomerLeadStatus_LeadType` (`lead_type_cd` ASC)
;

ALTER TABLE `gn_customer_link` 
 ADD INDEX `IXFK_CustomerLink_CustomerLinkType` (`customer_link_type_cd` ASC)
;

ALTER TABLE `gn_customer_link` 
 ADD INDEX `IXFK_CustomerLink_gn_customer` (`linked_customer_id` ASC)
;

ALTER TABLE `gn_customer_link` 
 ADD INDEX `IXFK_CustomerLink_gn_customer_02` (`customer_id` ASC)
;

ALTER TABLE `gn_customer_pay_method` 
 ADD INDEX `IXFK_gn_customer_pay_method_gn_customer` (`customer_id` ASC)
;

ALTER TABLE `gn_customer_pay_method` 
 ADD INDEX `IXFK_gn_customer_pay_method_gn_pay_method_type` (`pay_method_type_cd` ASC)
;

ALTER TABLE `gn_customer_role` 
 ADD INDEX `IXFK_CustomerRole_gn_customer` (`customer_id` ASC)
;

ALTER TABLE `gn_customer_role` 
 ADD INDEX `IXFK_CustomerRole_RoleType` (`role_type_cd` ASC)
;

ALTER TABLE `gn_email_template` 
 ADD INDEX `IXFK_email_template_association` (`association_id` ASC)
;

ALTER TABLE `gn_facility` 
 ADD INDEX `IXFK_gn_facility_gn_facility_type` (`facility_type_cd` ASC)
;

ALTER TABLE `gn_facility` 
 ADD INDEX `IXFK_gn_facility_gn_handicap_provider` (`handicap_provider_id` ASC)
;

ALTER TABLE `gn_golf_round` 
 ADD INDEX `IXFK_gn_golf_round_gn_course` (`course_id` ASC)
;

ALTER TABLE `gn_golf_round` 
 ADD INDEX `IXFK_gn_golf_round_gn_scoring_type` (`scoring_type_cd` ASC)
;

ALTER TABLE `gn_hole_score` 
 ADD INDEX `IXFK_gn_hole_score_gn_course_hole` (`course_hole_id` ASC)
;

ALTER TABLE `gn_hole_score` 
 ADD INDEX `IXFK_gn_hole_score_gn_course_score` (`course_score_id` ASC)
;

ALTER TABLE `gn_member_club` 
 ADD INDEX `IXFK_gn_member_club_gn_association` (`association_id` ASC)
;

ALTER TABLE `gn_member_club` 
 ADD INDEX `IXFK_gn_member_club_gn_member_club_type` (`member_club_type_cd` ASC)
;

ALTER TABLE `gn_member_club_zip` 
 ADD INDEX `IXFK_gn_member_club_zip_gn_member_club` (`club_id` ASC)
;

ALTER TABLE `gn_merchant_payment` 
 ADD INDEX `IXFK_gn_merchant_payment_gn_merchant_provider` (`merchant_provider_id` ASC)
;

ALTER TABLE `gn_shot_detail` 
 ADD INDEX `IXFK_gn_shot_detail_gn_golf_club_type` (`golf_club_type_cd` ASC)
;

ALTER TABLE `gn_shot_detail` 
 ADD INDEX `IXFK_gn_shot_detail_gn_hole_score` (`hole_score_id` ASC)
;

ALTER TABLE `gn_subscription` 
 ADD INDEX `IXFK_gn_subscription_gn_member_club_customer` (`club_customer_id` ASC)
;

ALTER TABLE `gn_subscription` 
 ADD INDEX `IXFK_gn_subscription_gn_membership_type` (`subscription_type_id` ASC)
;

ALTER TABLE `gn_subscription` 
 ADD INDEX `IXFK_gn_subscription_gn_renewal_status` (`renewal_status_cd` ASC)
;

ALTER TABLE `gn_subscription` 
 ADD INDEX `IXFK_gn_subscription_gn_subscription_status` (`subscription_status_cd` ASC)
;

ALTER TABLE `gn_subscription_club_filter` 
 ADD INDEX `IXFK_gn_subscription_club_filter_gn_club_service` (`club_service_id` ASC)
;

ALTER TABLE `gn_subscription_club_filter` 
 ADD INDEX `IXFK_gn_subscription_club_filter_gn_subscription_type` (`subscription_fee_id` ASC)
;

ALTER TABLE `gn_subscription_fee` 
 ADD INDEX `IXFK_gn_subscription_type_gn_association` (`association_id` ASC)
;

ALTER TABLE `gn_subscription_fee` 
 ADD INDEX `IXFK_gn_subscription_type_gn_fee_type_cd` (`fee_type_cd` ASC)
;

ALTER TABLE `gn_subscription_fee` 
 ADD INDEX `IXFK_gn_subscription_type_gn_gender_type` (`gender_type_cd` ASC)
;

ALTER TABLE `gn_subscription_fee` 
 ADD INDEX `IXFK_gn_subscription_type_gn_subscription_level` (`fee_level_cd` ASC)
;

ALTER TABLE `gn_subscription_fee` 
 ADD INDEX `IXFK_gn_subscription_type_gn_transaction_type` (`transaction_type_cd` ASC)
;

ALTER TABLE `gn_subscription_fee_map` 
 ADD INDEX `IXFK_gn_membership_subscription_gn_membership_type` (`subscription_type_id` ASC)
;

ALTER TABLE `gn_subscription_fee_map` 
 ADD INDEX `IXFK_gn_membership_subscription_gn_subscription_type` (`subscription_fee_id` ASC)
;

ALTER TABLE `gn_subscription_type` 
 ADD INDEX `IXFK_gn_membership_type_gn_club_service` (`club_service_id` ASC)
;

ALTER TABLE `gn_transaction` 
 ADD INDEX `IXFK_gn_online_transaction_gn_transaction_type` (`transaction_type_cd` ASC)
;

ALTER TABLE `gn_transaction` 
 ADD INDEX `IXFK_gn_transaction_gn_merchant_payment` (`merchant_payment_id` ASC)
;

ALTER TABLE `gn_transaction` 
 ADD INDEX `IXFK_gn_transaction_gn_subscription` (`subscription_id` ASC)
;

ALTER TABLE `gn_transaction` 
 ADD INDEX `IXFK_gn_transaction_gn_transaction_status` (`transaction_status_cd` ASC)
;

ALTER TABLE `gn_transaction_sub_detail` 
 ADD INDEX `IXFK_gn_transaction_sub_detail_gn_membership_fee` (`subscription_fee_id` ASC)
;

ALTER TABLE `gn_transaction_sub_detail` 
 ADD INDEX `IXFK_gn_transaction_sub_detail_gn_transaction` (`transaction_id` ASC)
;

ALTER TABLE `gn_user_audit` 
 ADD INDEX `IXFK_gn_user_audit_gn_customer` (`customer_id` ASC)
;

ALTER TABLE `gn_user_audit` 
 ADD INDEX `IXFK_gn_user_audit_gn_user_action_type` (`user_action_cd` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `gn_assn_bill_schedule` 
 ADD CONSTRAINT `FK_gn_assn_bill_schedule_gn_association`
	FOREIGN KEY (`association_id`) REFERENCES `gn_association` (`association_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `gn_assn_billing_settings` 
 ADD CONSTRAINT `FK_gn_assn_billing_settings_gn_association`
	FOREIGN KEY (`association_id`) REFERENCES `gn_association` (`association_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `gn_assn_billing_settings` 
 ADD CONSTRAINT `FK_gn_assn_billing_settings_gn_merchant_fee_bill_option`
	FOREIGN KEY (`merchant_fee_bill_cd`) REFERENCES `gn_merchant_fee_bill_option` (`merchant_fee_bill_cd`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `gn_assn_discount_rule` 
 ADD CONSTRAINT `FK_gn_assn_discount_rule_gn_association`
	FOREIGN KEY (`association_id`) REFERENCES `gn_association` (`association_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `gn_association` 
 ADD CONSTRAINT `FK_association_handicap_provider`
	FOREIGN KEY (`handicap_provider_id`) REFERENCES `gn_handicap_provider` (`handicap_provider_id`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_association_customer` 
 ADD CONSTRAINT `FK_association_customer_association`
	FOREIGN KEY (`association_id`) REFERENCES `gn_association` (`association_id`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_association_customer` 
 ADD CONSTRAINT `FK_association_customer_association_login_type`
	FOREIGN KEY (`assoc_login_type_cd`) REFERENCES `gn_association_login_type` (`assoc_login_type_cd`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_association_customer` 
 ADD CONSTRAINT `FK_association_customer_customer`
	FOREIGN KEY (`customer_id`) REFERENCES `gn_customer` (`customer_id`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_association_facility` 
 ADD CONSTRAINT `FK_gn_association_facility_gn_association`
	FOREIGN KEY (`association_id`) REFERENCES `gn_association` (`association_id`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_association_facility` 
 ADD CONSTRAINT `FK_gn_association_facility_gn_facility`
	FOREIGN KEY (`facility_id`) REFERENCES `gn_facility` (`facility_id`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_association_log` 
 ADD CONSTRAINT `FK_association_log_association`
	FOREIGN KEY (`association_id`) REFERENCES `gn_association` (`association_id`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_association_migration` 
 ADD CONSTRAINT `FK_gn_association_migration_gn_association`
	FOREIGN KEY (`association_id`) REFERENCES `gn_association` (`association_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `gn_association_settings` 
 ADD CONSTRAINT `FK_association_settings_association`
	FOREIGN KEY (`association_id`) REFERENCES `gn_association` (`association_id`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_association_settings` 
 ADD CONSTRAINT `FK_gn_association_settings_gn_merchant_provider`
	FOREIGN KEY (`merchant_provider_id`) REFERENCES `gn_merchant_provider` (`merchant_provider_id`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_association_zip_code` 
 ADD CONSTRAINT `FK_association_zip_code_association`
	FOREIGN KEY (`association_id`) REFERENCES `gn_association` (`association_id`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_club_bill` 
 ADD CONSTRAINT `FK_gn_club_bill_gn_club_service`
	FOREIGN KEY (`club_service_id`) REFERENCES `gn_club_service` (`club_service_id`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_club_bill` 
 ADD CONSTRAINT `FK_gn_club_bill_gn_payment_status`
	FOREIGN KEY (`bill_status_cd`) REFERENCES `gn_bill_status` (`bill_status_cd`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_club_bill_adjustment` 
 ADD CONSTRAINT `FK_gn_club_bill_adjustment_gn_bill_adjustment_type`
	FOREIGN KEY (`bill_adj_type_cd`) REFERENCES `gn_bill_adjustment_type` (`bill_adj_type_cd`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_club_bill_adjustment` 
 ADD CONSTRAINT `FK_gn_club_bill_adjustment_gn_club_service`
	FOREIGN KEY (`club_service_id`) REFERENCES `gn_club_service` (`club_service_id`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_club_bill_adjustment` 
 ADD CONSTRAINT `FK_gn_club_bill_adjustment_gn_club_bill`
	FOREIGN KEY (`club_bill_id`) REFERENCES `gn_club_bill` (`club_bill_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `gn_club_customer_field` 
 ADD CONSTRAINT `FK_gn_club_customer_field_gn_club_service_customer`
	FOREIGN KEY (`club_customer_id`) REFERENCES `gn_club_service_customer` (`club_customer_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `gn_club_field` 
 ADD CONSTRAINT `FK_gn_club_fields_gn_club_service`
	FOREIGN KEY (`club_service_id`) REFERENCES `gn_club_service` (`club_service_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `gn_club_payment` 
 ADD CONSTRAINT `FK_gn_club_payment_gn_club_service`
	FOREIGN KEY (`club_service_id`) REFERENCES `gn_club_service` (`club_service_id`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_club_payment` 
 ADD CONSTRAINT `FK_gn_club_payment_gn_merchant_payment`
	FOREIGN KEY (`merchant_payment_id`) REFERENCES `gn_merchant_payment` (`merchant_payment_id`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_club_payment` 
 ADD CONSTRAINT `FK_gn_club_payment_gn_payment_type`
	FOREIGN KEY (`payment_type_cd`) REFERENCES `gn_payment_type` (`payment_type_cd`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_club_payment` 
 ADD CONSTRAINT `FK_gn_club_payment_gn_club_bill`
	FOREIGN KEY (`club_bill_id`) REFERENCES `gn_club_bill` (`club_bill_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `gn_club_payment` 
 ADD CONSTRAINT `FK_gn_club_payment_gn_club_bill_adjustment`
	FOREIGN KEY (`club_bill_adj_id`) REFERENCES `gn_club_bill_adjustment` (`club_bill_adj_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `gn_club_payment_check` 
 ADD CONSTRAINT `FK_gn_club_payment_check_gn_club_payment`
	FOREIGN KEY (`club_payment_id`) REFERENCES `gn_club_payment` (`club_payment_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `gn_club_payment_detail` 
 ADD CONSTRAINT `FK_gn_club_payment_detail_gn_club_bill_adjustment`
	FOREIGN KEY (`club_bill_adj_id`) REFERENCES `gn_club_bill_adjustment` (`club_bill_adj_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `gn_club_payment_detail` 
 ADD CONSTRAINT `FK_gn_club_payment_detail_gn_club_payment`
	FOREIGN KEY (`club_payment_id`) REFERENCES `gn_club_payment` (`club_payment_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `gn_club_payment_detail` 
 ADD CONSTRAINT `FK_gn_club_payment_detail_gn_transaction`
	FOREIGN KEY (`transaction_id`) REFERENCES `gn_transaction` (`transaction_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `gn_club_service` 
 ADD CONSTRAINT `FK_gn_club_service_gn_member_club`
	FOREIGN KEY (`club_id`) REFERENCES `gn_member_club` (`club_id`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_club_service` 
 ADD CONSTRAINT `FK_gn_club_service_gn_gender_type`
	FOREIGN KEY (`gender_type_cd`) REFERENCES `gn_gender_type` (`gender_type_cd`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `gn_club_service_contact` 
 ADD CONSTRAINT `FK_gn_club_service_contact_gn_club_service`
	FOREIGN KEY (`club_service_id`) REFERENCES `gn_club_service` (`club_service_id`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_club_service_contact` 
 ADD CONSTRAINT `FK_gn_club_service_contact_gn_contact_type`
	FOREIGN KEY (`contact_type_cd`) REFERENCES `gn_club_contact_type` (`contact_type_cd`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_club_service_contact` 
 ADD CONSTRAINT `FK_gn_club_service_contact_gn_customer`
	FOREIGN KEY (`customer_id`) REFERENCES `gn_customer` (`customer_id`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_club_service_customer` 
 ADD CONSTRAINT `FK_gn_member_club_customer_gn_customer`
	FOREIGN KEY (`customer_id`) REFERENCES `gn_customer` (`customer_id`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_club_service_customer` 
 ADD CONSTRAINT `FK_gn_member_club_customer_gn_member_status`
	FOREIGN KEY (`member_status_cd`) REFERENCES `gn_member_status` (`member_status_cd`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_club_service_customer` 
 ADD CONSTRAINT `FK_gn_member_club_service_customer_gn_member_club_service`
	FOREIGN KEY (`club_service_id`) REFERENCES `gn_club_service` (`club_service_id`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_club_service_settings` 
 ADD CONSTRAINT `FK_gn_club_service_settings_gn_calendar_year_type`
	FOREIGN KEY (`calendar_year_type_cd`) REFERENCES `gn_calendar_year_type` (`calendar_year_type_cd`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_club_service_settings` 
 ADD CONSTRAINT `FK_gn_club_service_settings_gn_club_service`
	FOREIGN KEY (`club_service_id`) REFERENCES `gn_club_service` (`club_service_id`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_course` 
 ADD CONSTRAINT `FK_gn_course_gn_facility`
	FOREIGN KEY (`facility_id`) REFERENCES `gn_facility` (`facility_id`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_course_customer_link` 
 ADD CONSTRAINT `FK_gn_course_customer_link_gn_course`
	FOREIGN KEY (`course_id`) REFERENCES `gn_course` (`course_id`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_course_customer_link` 
 ADD CONSTRAINT `FK_gn_course_customer_link_gn_course_link_type`
	FOREIGN KEY (`course_link_type_cd`) REFERENCES `gn_course_link_type` (`course_link_type_cd`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_course_customer_link` 
 ADD CONSTRAINT `FK_gn_course_customer_link_gn_customer`
	FOREIGN KEY (`customer_id`) REFERENCES `gn_customer` (`customer_id`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_course_hole` 
 ADD CONSTRAINT `FK_gn_course_hole_gn_course`
	FOREIGN KEY (`course_id`) REFERENCES `gn_course` (`course_id`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_course_score` 
 ADD CONSTRAINT `FK_gn_course_score_gn_course`
	FOREIGN KEY (`course_id`) REFERENCES `gn_course` (`course_id`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_course_score` 
 ADD CONSTRAINT `FK_gn_course_score_gn_course_tee`
	FOREIGN KEY (`course_tee_id`) REFERENCES `gn_course_tee` (`course_tee_id`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_course_score` 
 ADD CONSTRAINT `FK_gn_course_score_gn_customer`
	FOREIGN KEY (`customer_id`) REFERENCES `gn_customer` (`customer_id`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_course_score` 
 ADD CONSTRAINT `FK_gn_course_score_gn_golf_round`
	FOREIGN KEY (`golf_round_id`) REFERENCES `gn_golf_round` (`golf_round_id`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_course_tee` 
 ADD CONSTRAINT `FK_gn_course_tee_gn_course`
	FOREIGN KEY (`course_id`) REFERENCES `gn_course` (`course_id`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_course_tee` 
 ADD CONSTRAINT `FK_gn_course_tee_gn_tee_rating`
	FOREIGN KEY (`tee_rating_cd`) REFERENCES `gn_tee_rating` (`tee_rating_cd`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_customer_address` 
 ADD CONSTRAINT `FK_CustomerAddress_AddressType`
	FOREIGN KEY (`address_type_cd`) REFERENCES `gn_address_type` (`address_type_cd`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_customer_address` 
 ADD CONSTRAINT `FK_CustomerAddress_gn_customer`
	FOREIGN KEY (`customer_id`) REFERENCES `gn_customer` (`customer_id`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_customer_contact` 
 ADD CONSTRAINT `FK_CustomerContact_ContactType`
	FOREIGN KEY (`contact_type_cd`) REFERENCES `gn_contact_type` (`contact_type_cd`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_customer_contact` 
 ADD CONSTRAINT `FK_CustomerContact_gn_customer`
	FOREIGN KEY (`customer_id`) REFERENCES `gn_customer` (`customer_id`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_customer_golf_clubs` 
 ADD CONSTRAINT `FK_gn_customer_clubs_gn_club_type`
	FOREIGN KEY (`golf_club_type_cd`) REFERENCES `gn_golf_club_type` (`golf_club_type_cd`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_customer_golf_clubs` 
 ADD CONSTRAINT `FK_gn_customer_clubs_gn_customer`
	FOREIGN KEY (`customer_id`) REFERENCES `gn_customer` (`customer_id`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_customer_lead_status` 
 ADD CONSTRAINT `FK_CustomerLeadStatus_gn_customer`
	FOREIGN KEY (`customer_id`) REFERENCES `gn_customer` (`customer_id`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_customer_lead_status` 
 ADD CONSTRAINT `FK_CustomerLeadStatus_LeadType`
	FOREIGN KEY (`lead_type_cd`) REFERENCES `gn_lead_type` (`lead_type_cd`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_customer_link` 
 ADD CONSTRAINT `FK_CustomerLink_CustomerLinkType`
	FOREIGN KEY (`customer_link_type_cd`) REFERENCES `gn_customer_link_type` (`customer_link_type_cd`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_customer_link` 
 ADD CONSTRAINT `FK_CustomerLink_gn_customer`
	FOREIGN KEY (`linked_customer_id`) REFERENCES `gn_customer` (`customer_id`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_customer_link` 
 ADD CONSTRAINT `FK_CustomerLink_gn_customer_02`
	FOREIGN KEY (`customer_id`) REFERENCES `gn_customer` (`customer_id`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_customer_pay_method` 
 ADD CONSTRAINT `FK_gn_customer_pay_method_gn_customer`
	FOREIGN KEY (`customer_id`) REFERENCES `gn_customer` (`customer_id`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_customer_pay_method` 
 ADD CONSTRAINT `FK_gn_customer_pay_method_gn_pay_method_type`
	FOREIGN KEY (`pay_method_type_cd`) REFERENCES `gn_pay_method_type` (`pay_method_type_cd`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_customer_role` 
 ADD CONSTRAINT `FK_CustomerRole_gn_customer`
	FOREIGN KEY (`customer_id`) REFERENCES `gn_customer` (`customer_id`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_customer_role` 
 ADD CONSTRAINT `FK_CustomerRole_RoleType`
	FOREIGN KEY (`role_type_cd`) REFERENCES `gn_role_type` (`role_type_cd`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_email_template` 
 ADD CONSTRAINT `FK_email_template_association`
	FOREIGN KEY (`association_id`) REFERENCES `gn_association` (`association_id`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_facility` 
 ADD CONSTRAINT `FK_gn_facility_gn_facility_type`
	FOREIGN KEY (`facility_type_cd`) REFERENCES `gn_facility_type` (`facility_type_cd`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_facility` 
 ADD CONSTRAINT `FK_gn_facility_gn_handicap_provider`
	FOREIGN KEY (`handicap_provider_id`) REFERENCES `gn_handicap_provider` (`handicap_provider_id`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_golf_round` 
 ADD CONSTRAINT `FK_gn_golf_round_gn_course`
	FOREIGN KEY (`course_id`) REFERENCES `gn_course` (`course_id`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_golf_round` 
 ADD CONSTRAINT `FK_gn_golf_round_gn_scoring_type`
	FOREIGN KEY (`scoring_type_cd`) REFERENCES `gn_scoring_type` (`scoring_type_cd`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `gn_hole_score` 
 ADD CONSTRAINT `FK_gn_hole_score_gn_course_hole`
	FOREIGN KEY (`course_hole_id`) REFERENCES `gn_course_hole` (`course_hole_id`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_hole_score` 
 ADD CONSTRAINT `FK_gn_hole_score_gn_course_score`
	FOREIGN KEY (`course_score_id`) REFERENCES `gn_course_score` (`course_score_id`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_hp_synch_queue` 
 ADD CONSTRAINT `FK_gn_hp_synch_queue_gn_club_service_customer`
	FOREIGN KEY (`club_customer_id`) REFERENCES `gn_club_service_customer` (`club_customer_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `gn_hp_synch_queue` 
 ADD CONSTRAINT `FK_gn_hp_synch_queue_gn_synch_status`
	FOREIGN KEY (`synch_status_cd`) REFERENCES `gn_synch_status` (`synch_status_cd`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `gn_member_club` 
 ADD CONSTRAINT `FK_gn_member_club_gn_association`
	FOREIGN KEY (`association_id`) REFERENCES `gn_association` (`association_id`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_member_club` 
 ADD CONSTRAINT `FK_gn_member_club_gn_member_club_type`
	FOREIGN KEY (`member_club_type_cd`) REFERENCES `gn_member_club_type` (`member_club_type_cd`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `gn_member_club_migration` 
 ADD CONSTRAINT `FK_gn_member_club_migration_gn_member_club`
	FOREIGN KEY (`club_id`) REFERENCES `gn_member_club` (`club_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `gn_member_club_zip` 
 ADD CONSTRAINT `FK_gn_member_club_zip_gn_member_club`
	FOREIGN KEY (`club_id`) REFERENCES `gn_member_club` (`club_id`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_merchant_payment` 
 ADD CONSTRAINT `FK_gn_merchant_payment_gn_merchant_provider`
	FOREIGN KEY (`merchant_provider_id`) REFERENCES `gn_merchant_provider` (`merchant_provider_id`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_merchant_payment` 
 ADD CONSTRAINT `FK_gn_merchant_payment_gn_merchant_status`
	FOREIGN KEY (`merchant_status_cd`) REFERENCES `gn_merchant_status` (`merchant_status_cd`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `gn_merchant_synch_queue` 
 ADD CONSTRAINT `FK_gn_merchant_synch_queue_gn_merchant_payment`
	FOREIGN KEY (`merchant_payment_id`) REFERENCES `gn_merchant_payment` (`merchant_payment_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `gn_merchant_synch_queue` 
 ADD CONSTRAINT `FK_gn_merchant_synch_queue_gn_synch_status`
	FOREIGN KEY (`synch_status_cd`) REFERENCES `gn_synch_status` (`synch_status_cd`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `gn_shot_detail` 
 ADD CONSTRAINT `FK_gn_shot_detail_gn_golf_club_type`
	FOREIGN KEY (`golf_club_type_cd`) REFERENCES `gn_golf_club_type` (`golf_club_type_cd`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_shot_detail` 
 ADD CONSTRAINT `FK_gn_shot_detail_gn_hole_score`
	FOREIGN KEY (`hole_score_id`) REFERENCES `gn_hole_score` (`hole_score_id`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_subscription` 
 ADD CONSTRAINT `FK_gn_subscription_gn_member_club_customer`
	FOREIGN KEY (`club_customer_id`) REFERENCES `gn_club_service_customer` (`club_customer_id`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_subscription` 
 ADD CONSTRAINT `FK_gn_subscription_gn_subscription_status`
	FOREIGN KEY (`subscription_status_cd`) REFERENCES `gn_subscription_status` (`subscription_status_cd`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_subscription` 
 ADD CONSTRAINT `FK_gn_subscription_gn_membership_type`
	FOREIGN KEY (`subscription_type_id`) REFERENCES `gn_subscription_type` (`subscription_type_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `gn_subscription` 
 ADD CONSTRAINT `FK_gn_subscription_gn_renewal_status`
	FOREIGN KEY (`renewal_status_cd`) REFERENCES `gn_renewal_status` (`renewal_status_cd`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `gn_subscription_club_filter` 
 ADD CONSTRAINT `FK_gn_subscription_club_filter_gn_subscription_type`
	FOREIGN KEY (`subscription_fee_id`) REFERENCES `gn_subscription_fee` (`subscription_fee_id`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_subscription_club_filter` 
 ADD CONSTRAINT `FK_gn_subscription_club_filter_gn_club_service`
	FOREIGN KEY (`club_service_id`) REFERENCES `gn_club_service` (`club_service_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `gn_subscription_fee` 
 ADD CONSTRAINT `FK_gn_subscription_type_gn_association`
	FOREIGN KEY (`association_id`) REFERENCES `gn_association` (`association_id`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_subscription_fee` 
 ADD CONSTRAINT `FK_gn_subscription_type_gn_fee_type_cd`
	FOREIGN KEY (`fee_type_cd`) REFERENCES `gn_fee_type` (`fee_type_cd`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_subscription_fee` 
 ADD CONSTRAINT `FK_gn_subscription_type_gn_gender_type`
	FOREIGN KEY (`gender_type_cd`) REFERENCES `gn_gender_type` (`gender_type_cd`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_subscription_fee` 
 ADD CONSTRAINT `FK_gn_subscription_type_gn_subscription_level`
	FOREIGN KEY (`fee_level_cd`) REFERENCES `gn_fee_level` (`fee_level_cd`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_subscription_fee` 
 ADD CONSTRAINT `FK_gn_subscription_type_gn_transaction_type`
	FOREIGN KEY (`transaction_type_cd`) REFERENCES `gn_transaction_type` (`transaction_type_cd`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_subscription_fee_map` 
 ADD CONSTRAINT `FK_gn_membership_subscription_gn_membership_type`
	FOREIGN KEY (`subscription_type_id`) REFERENCES `gn_subscription_type` (`subscription_type_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `gn_subscription_fee_map` 
 ADD CONSTRAINT `FK_gn_membership_subscription_gn_subscription_type`
	FOREIGN KEY (`subscription_fee_id`) REFERENCES `gn_subscription_fee` (`subscription_fee_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `gn_subscription_type` 
 ADD CONSTRAINT `FK_gn_membership_type_gn_club_service`
	FOREIGN KEY (`club_service_id`) REFERENCES `gn_club_service` (`club_service_id`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_transaction` 
 ADD CONSTRAINT `FK_gn_online_transaction_gn_transaction_type`
	FOREIGN KEY (`transaction_type_cd`) REFERENCES `gn_transaction_type` (`transaction_type_cd`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_transaction` 
 ADD CONSTRAINT `FK_gn_transaction_gn_merchant_payment`
	FOREIGN KEY (`merchant_payment_id`) REFERENCES `gn_merchant_payment` (`merchant_payment_id`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_transaction` 
 ADD CONSTRAINT `FK_gn_transaction_gn_transaction_status`
	FOREIGN KEY (`transaction_status_cd`) REFERENCES `gn_transaction_status` (`transaction_status_cd`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `gn_transaction` 
 ADD CONSTRAINT `FK_gn_transaction_gn_club_bill`
	FOREIGN KEY (`club_bill_id`) REFERENCES `gn_club_bill` (`club_bill_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `gn_transaction` 
 ADD CONSTRAINT `FK_gn_transaction_gn_club_bill_adjustment`
	FOREIGN KEY (`club_bill_adj_id`) REFERENCES `gn_club_bill_adjustment` (`club_bill_adj_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `gn_transaction` 
 ADD CONSTRAINT `FK_gn_transaction_gn_subscription`
	FOREIGN KEY (`subscription_id`) REFERENCES `gn_subscription` (`subscription_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `gn_transaction_sub_detail` 
 ADD CONSTRAINT `FK_gn_transaction_sub_detail_gn_membership_fee`
	FOREIGN KEY (`subscription_fee_id`) REFERENCES `gn_subscription_fee` (`subscription_fee_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `gn_transaction_sub_detail` 
 ADD CONSTRAINT `FK_gn_transaction_sub_detail_gn_transaction`
	FOREIGN KEY (`transaction_id`) REFERENCES `gn_transaction` (`transaction_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `gn_user_audit` 
 ADD CONSTRAINT `FK_gn_user_audit_gn_customer`
	FOREIGN KEY (`customer_id`) REFERENCES `gn_customer` (`customer_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `gn_user_audit` 
 ADD CONSTRAINT `FK_gn_user_audit_gn_user_action_type`
	FOREIGN KEY (`user_action_cd`) REFERENCES `gn_user_action_type` (`user_action_cd`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1 
;

/* Create Views */

CREATE VIEW gn_payment_history_view AS
SELECT uuid_short() as id, 'bill' as item_type, club_bill_id as item_id, club_service_id, date_add(end_bill_date, interval 23 hour) as date, CONCAT(DATE_FORMAT(end_bill_date, '%M, %Y'), ' Bill') as description, bill_amount as amount, amount_due as balance
FROM gn_club_bill
UNION ALL
SELECT uuid_short() as id, 'payment' as item_type, club_payment_id as item_id, club_service_id, payment_date as date, (CASE WHEN payment_amount >= 0 THEN 'Payment to Association' ELSE 'Payment to Club' END) as description, (payment_amount * -1) as amount, null as balance
FROM gn_club_payment
UNION ALL
SELECT uuid_short() as id, 'adjustment' as item_type, club_bill_adj_id as item_id, club_service_id, adj_date as date, adj_description as description, adj_amount as amount, null as balance
FROM gn_club_bill_adjustment
WHERE bill_adj_type_cd = 'tx_credit';

;
